name: Unity-InGameDebugConsole CI/CD Pipeline

on:
  push:
    branches:
      - main #will be triggered if a push is made to the main branch
    tags:
      - 'v*' #or a new version is added

jobs:
  build:
    name: Build Unity Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 #get latest code from repo

#      - name: Clean Unity License Cache #to avoid license generation issues
#        run: |
#          rm -rf ~/.local/share/unity3d
#          rm -rf ~/.unity3d

      - name: Decode and Save Unity License
        run: echo "${{ secrets.UNITY_LICENSE }}" | base64 --decode > UnityLicense.ulf

      - name: Verify License File
        run: cat UnityLicense.ulf

      - name: Activate Unity License #manually activate a license
        uses: game-ci/unity-activate@v2
        with:
          activationMethod: personal
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Setup Unity
        uses: game-ci/unity-builder@v4
#        with:
#            unityVersion: 6000.0.33f1

      - name: Export Unitypackage
        run: |
          mkdir -p build
          unity-editor -quit -batchmode -nographics -logfile \
            -projectPath . \
            -exportPackage "Assets/InGameDebugConsole" "build/InGameDebugConsole.unitypackage"


      - name: Upload Unitypackage as Artifact
        uses: actions/upload-artifact@v4 #had to change from v3 to v4 (v3 is deprecated)
        with:
          name: InGameDebugConsole
          path: build/InGameDebugConsole.unitypackage

  release:
    name: Create Github Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Unity Package
        uses: actions/download-artifact@v4 #v3 is deprecated as of 2024
        with:
          name: UnityPackage
          path: Build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/InGameDebugConsole.unitypackage
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "New release for the In-Game Debug Console."
          draft: false
          prerelease: false
          
